#!/usr/bin/env python3
"""Regenerate the reloc-resolved watchdog disassembly artifacts.

Outputs (paths relative to the repository root):
    artifacts/guard_post_handler.s   full kill chain, relocations filled in
    artifacts/guard_disasm.txt       same, plus the heap-spray detector module
    artifacts/guard_relocs.txt       raw relocation dump for .text

Requires the vendor modules, which are NOT redistributed (see NOTICE.md):

    adb pull /vendor/lib/modules/oplus_security_guard.ko
    adb pull /vendor/lib/modules/oplus_secure_harden.ko

Usage:  python tools/gen_guard_disasm.py <guard.ko> <harden.ko> [outdir]
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOL = os.path.join(HERE, "kdis_ko_reloc.py")

# The kill chain, in the order a reader needs it.
CHAIN = [
    ("oplus_root_check_pre_handler", None),
    ("oplus_root_check_post_handler", None),
    ("oplus_root_killed", None),
    ("oplus_root_check_succ", None),
    ("oplus_exe_block_ret_handler", None),
    ("oplus_RWO_root_check", None),
    ("oplus_harden_pre_handler", None),
    ("oplus_boot_state_init", None),
    ("is_unlocked", None),
]
HARDEN = [
    ("entry_handler_socket", None),
    ("entry_handler_setxattr", None),
    ("entry_handler_cpuinfo", None),
    ("oplus_heapspray_check", None),
]

HEADER = """\
# {title}
#
# Generated by tools/gen_guard_disasm.py from {src} (not redistributed).
# Relocations are resolved via the RELA section whose sh_info points at .text;
# on these builds that section is named `.rela.text.__cfi_check`, so a
# name-based lookup finds nothing. Targets that are section symbols (no name in
# .strtab, identity in st_shndx) are printed as `<section>+<addend>` -- that is
# how `g_boot_state` is located: it is the ONLY byte in `.data..ro_after_init`,
# and the watchdog reads it as a single LDRB.
#
# Rebuild:
#   python tools/gen_guard_disasm.py <guard.ko> <harden.ko> [outdir]
#
"""


def run(*args):
    r = subprocess.run([sys.executable, TOOL, *args], capture_output=True,
                       text=True)
    if r.returncode != 0:
        raise SystemExit(f"{TOOL} {' '.join(args)} failed:\n{r.stderr}")
    return r.stdout


def run_exempt(guard):
    """Decode the 72-entry jump table at .rodata+0 with real syscall names."""
    gen = os.path.join(HERE, "gen_exempt_table.py")
    if not os.path.exists(gen):
        return "(tools/gen_exempt_table.py not present)\n"
    r = subprocess.run([sys.executable, gen, guard], capture_output=True,
                       text=True)
    if r.returncode != 0:
        return f"(gen_exempt_table.py failed)\n{r.stderr}\n"
    return r.stdout


def section(title, ko, syms, banner=True):
    out = []
    for sym, _ in syms:
        try:
            out.append(run(ko, sym))
        except SystemExit as e:
            out.append(f"### {sym}\n!! not present in this build: {e}\n")
    if banner:
        out.insert(0, f"\n{'=' * 78}\n== {title}\n{'=' * 78}\n")
    return "\n".join(out)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 1
    guard, harden = sys.argv[1], sys.argv[2]
    outdir = sys.argv[3] if len(sys.argv) > 3 else os.path.join(HERE, "..",
                                                                "artifacts")
    os.makedirs(outdir, exist_ok=True)

    chain = HEADER.format(title="oplus_security_guard.ko - kill chain, "
                                "relocations resolved",
                          src=os.path.basename(guard))
    chain += section("kill chain", guard, CHAIN)
    chain += ("\n" + "=" * 78 + "\n== kill-path jump table (.rodata+0), "
              "with the real arm64 syscall names\n" + "=" * 78 + "\n\n")
    chain += run_exempt(guard)
    chain += "\n"
    chain += run(guard, "--relocs", ".text")
    with open(os.path.join(outdir, "guard_post_handler.s"), "w") as f:
        f.write(chain)

    full = HEADER.format(title="OPPO watchdog + heap-spray detector - "
                               "relocations resolved",
                         src=f"{os.path.basename(guard)} + "
                             f"{os.path.basename(harden)}")
    full += section("oplus_security_guard.ko", guard, CHAIN)
    full += section("oplus_secure_harden.ko", harden, HARDEN)
    with open(os.path.join(outdir, "guard_disasm.txt"), "w") as f:
        f.write(full)

    with open(os.path.join(outdir, "guard_relocs.txt"), "w") as f:
        f.write("# .text relocations, oplus_security_guard.ko\n")
        f.write(run(guard, "--relocs", ".text"))
        f.write("\n# .text relocations, oplus_secure_harden.ko\n")
        f.write(run(harden, "--relocs", ".text"))

    print(f"wrote guard_post_handler.s, guard_disasm.txt, guard_relocs.txt "
          f"to {os.path.abspath(outdir)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
