# oplus_security_guard.ko - kill chain, relocations resolved
#
# Generated by tools/gen_guard_disasm.py from oplus_security_guard.ko (not redistributed).
# Relocations are resolved via the RELA section whose sh_info points at .text;
# on these builds that section is named `.rela.text.__cfi_check`, so a
# name-based lookup finds nothing. Targets that are section symbols (no name in
# .strtab, identity in st_shndx) are printed as `<section>+<addend>` -- that is
# how `g_boot_state` is located: it is the ONLY byte in `.data..ro_after_init`,
# and the watchdog reads it as a single LDRB.
#
# Rebuild:
#   python tools/gen_guard_disasm.py <guard.ko> <harden.ko> [outdir]
#

==============================================================================
== kill chain
==============================================================================

### oplus_root_check_pre_handler
=== .text+0x3ac  (size 0x3c) ===

  0x03ac: paciasp 
  0x03b0: ldrsw   x8, [x1, #0x118]
  0x03b4: mrs     x9, sp_el0
  0x03b8: ldr     x10, [x9, #0x780]
  0x03bc: str     x8, [x9, #0xdf8]
  0x03c0: ldr     w8, [x10, #4]
  0x03c4: str     x8, [x9, #0xe00]
  0x03c8: ldr     w8, [x10, #0x14]
  0x03cc: str     x8, [x9, #0xe08]
  0x03d0: ldr     w8, [x10, #8]
  0x03d4: str     x8, [x9, #0xe10]
  0x03d8: ldr     w8, [x10, #0x18]
  0x03dc: str     x8, [x9, #0xe18]
  0x03e0: autiasp 
  0x03e4: ret     


### oplus_root_check_post_handler
=== .text+0x3e8  (size 0xcc) ===

  0x03e8: paciasp 
  0x03ec: str     x30, [x18], #8
  0x03f0: stp     x29, x30, [sp, #-0x10]!
  0x03f4: mov     x29, sp
  0x03f8: mrs     x8, sp_el0
  0x03fc: ldr     x0, [x8, #0xe00]
  0x0400: cbz     x0, #0x48c
  0x0404: adrp    x9, #0   ; ADR_PREL_PG_HI21 + LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x0408: ldrb    w9, [x9]   ; LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x040c: tbnz    w9, #0, #0x48c
  0x0410: ldr     x9, [x8, #0x780]
  0x0414: ldr     w3, [x8, #0xdf8]
  0x0418: ldr     w10, [x9, #4]
  0x041c: cmp     x0, x10
  0x0420: b.hi    #0x468
  0x0424: ldr     x10, [x8, #0xe08]
  0x0428: ldr     w11, [x9, #0x14]
  0x042c: cmp     x10, x11
  0x0430: b.hi    #0x468
  0x0434: ldr     x10, [x8, #0xe10]
  0x0438: ldr     w11, [x9, #8]
  0x043c: cmp     x10, x11
  0x0440: b.hi    #0x468
  0x0444: ldr     x10, [x8, #0xe18]
  0x0448: ldr     w9, [x9, #0x18]
  0x044c: cmp     x10, x9
  0x0450: b.hi    #0x468
  0x0454: ldr     x9, [x8, #8]
  0x0458: mov     x10, #1
  0x045c: movk    x10, #0x80, lsl #32
  0x0460: cmp     x9, x10
  0x0464: b.lo    #0x48c
  0x0468: sub     w9, w3, #0x8f
  0x046c: cmp     w9, #0x47
  0x0470: b.hi    #0x4a0
  0x0474: adrp    x10, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata
  0x0478: add     x10, x10, #0   ; ADD_ABS_LO12_NC -> .rodata
  0x047c: adr     x11, #0x47c
  0x0480: ldrsw   x12, [x10, x9, lsl #2]
  0x0484: add     x11, x11, x12
  0x0488: br      x11
  0x048c: bti     j
  0x0490: ldp     x29, x30, [sp], #0x10
  0x0494: ldr     x30, [x18, #-8]!
  0x0498: autiasp 
  0x049c: ret     
  0x04a0: bti     j
  0x04a4: ldr     w1, [x8, #0xe08]
  0x04a8: ldr     w2, [x8, #0xe18]
  0x04ac: bl      #0x4ac   ; CALL26 -> oplus_root_check_succ
  0x04b0: bl      #0x4b0   ; CALL26 -> oplus_root_killed


### oplus_root_killed
=== .text+0x388  (size 0x24) ===

  0x0388: paciasp 
  0x038c: str     x30, [x18], #8
  0x0390: stp     x29, x30, [sp, #-0x10]!
  0x0394: mov     x29, sp
  0x0398: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x976
  0x039c: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x976
  0x03a0: bl      #0x3a0   ; CALL26 -> printk
  0x03a4: mov     w0, #9
  0x03a8: bl      #0x3a8   ; CALL26 -> do_exit


### oplus_root_check_succ
=== .text+0x14c  (size 0x238) ===

  0x014c: paciasp 
  0x0150: str     x30, [x18], #8
  0x0154: stp     x29, x30, [sp, #-0x60]!
  0x0158: stp     x28, x27, [sp, #0x10]
  0x015c: stp     x26, x25, [sp, #0x20]
  0x0160: stp     x24, x23, [sp, #0x30]
  0x0164: stp     x22, x21, [sp, #0x40]
  0x0168: stp     x20, x19, [sp, #0x50]
  0x016c: mov     x29, sp
  0x0170: sub     sp, sp, #0x1b0
  0x0174: adrp    x8, #0   ; ADR_PREL_PG_HI21 + LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x0178: ldr     x8, [x8]   ; LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x017c: mov     w20, w2
  0x0180: mov     w21, w1
  0x0184: mov     w22, w0
  0x0188: add     x0, sp, #0x60
  0x018c: mov     w2, #0x140
  0x0190: mov     w1, wzr
  0x0194: mov     w19, w3
  0x0198: stur    x8, [x29, #-0x10]
  0x019c: bl      #0x19c   ; CALL26 -> memset
  0x01a0: stp     xzr, xzr, [sp, #0x50]
  0x01a4: stp     xzr, xzr, [sp, #0x40]
  0x01a8: mrs     x24, sp_el0
  0x01ac: add     x8, x24, #0x5d8
  0x01b0: ldar    x23, [x8]
  0x01b4: cbz     x23, #0x1d0
  0x01b8: add     x0, sp, #0x40
  0x01bc: mov     w1, #0x10
  0x01c0: mov     x2, x23
  0x01c4: bl      #0x1c4   ; CALL26 -> __get_task_comm
  0x01c8: ldr     w26, [x23, #0x5c8]
  0x01cc: b       #0x1d4
  0x01d0: mov     w26, #-1
  0x01d4: mov     w8, #0x6576
  0x01d8: adrp    x9, #0   ; ADR_PREL_PG_HI21 -> .rodata+0xb0f
  0x01dc: movk    w8, #0x746e, lsl #16
  0x01e0: add     x9, x9, #0   ; ADD_ABS_LO12_NC -> .rodata+0xb0f
  0x01e4: stur    x8, [sp, #0x6c]
  0x01e8: ldr     x8, [x9]
  0x01ec: adrp    x9, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0xad0
  0x01f0: add     x9, x9, #0   ; ADD_ABS_LO12_NC -> .rodata+0xad0
  0x01f4: ldr     x9, [x9]
  0x01f8: stur    x8, [sp, #0x64]
  0x01fc: adrp    x8, #0   ; ADR_PREL_PG_HI21 + LDST64_ABS_LO12_NC -> kmalloc_caches+0x40
  0x0200: ldr     x0, [x8]   ; LDST64_ABS_LO12_NC -> kmalloc_caches+0x40
  0x0204: mov     w10, #0x6b63
  0x0208: mov     w1, #0xa20
  0x020c: mov     w2, #0x100
  0x0210: stur    x10, [sp, #0x8c]
  0x0214: str     wzr, [sp, #0x60]
  0x0218: stur    x9, [sp, #0x84]
  0x021c: stur    xzr, [sp, #0x74]
  0x0220: stur    xzr, [sp, #0x7c]
  0x0224: str     wzr, [sp, #0x94]
  0x0228: bl      #0x228   ; CALL26 -> kmem_cache_alloc_trace
  0x022c: cbnz    x0, #0x26c
  0x0230: adrp    x9, #0   ; ADR_PREL_PG_HI21 -> __stack_chk_guard
  0x0234: ldur    x8, [x29, #-0x10]
  0x0238: ldr     x9, [x9]   ; LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x023c: cmp     x9, x8
  0x0240: b.ne    #0x380
  0x0244: add     sp, sp, #0x1b0
  0x0248: ldp     x20, x19, [sp, #0x50]
  0x024c: ldp     x22, x21, [sp, #0x40]
  0x0250: ldp     x24, x23, [sp, #0x30]
  0x0254: ldp     x26, x25, [sp, #0x20]
  0x0258: ldp     x28, x27, [sp, #0x10]
  0x025c: ldp     x29, x30, [sp], #0x60
  0x0260: ldr     x30, [x18, #-8]!
  0x0264: autiasp 
  0x0268: ret     
  0x026c: stp     xzr, xzr, [x0, #0xf0]
  0x0270: stp     xzr, xzr, [x0, #0xe0]
  0x0274: stp     xzr, xzr, [x0, #0xd0]
  0x0278: stp     xzr, xzr, [x0, #0xc0]
  0x027c: stp     xzr, xzr, [x0, #0xb0]
  0x0280: stp     xzr, xzr, [x0, #0xa0]
  0x0284: stp     xzr, xzr, [x0, #0x90]
  0x0288: stp     xzr, xzr, [x0, #0x80]
  0x028c: stp     xzr, xzr, [x0, #0x70]
  0x0290: stp     xzr, xzr, [x0, #0x60]
  0x0294: stp     xzr, xzr, [x0, #0x50]
  0x0298: stp     xzr, xzr, [x0, #0x40]
  0x029c: stp     xzr, xzr, [x0, #0x30]
  0x02a0: stp     xzr, xzr, [x0, #0x20]
  0x02a4: stp     xzr, xzr, [x0, #0x10]
  0x02a8: stp     xzr, xzr, [x0]
  0x02ac: ldr     x8, [x24, #0x780]
  0x02b0: ldr     x9, [x24, #8]
  0x02b4: mov     x23, x0
  0x02b8: add     x0, sp, #0x50
  0x02bc: ldr     w27, [x8, #4]
  0x02c0: ldp     w28, w25, [x8, #0x14]
  0x02c4: mov     w1, #0x10
  0x02c8: mov     x2, x24
  0x02cc: str     x9, [sp, #0x38]
  0x02d0: bl      #0x2d0   ; CALL26 -> __get_task_comm
  0x02d4: ldr     x7, [sp, #0x38]
  0x02d8: adrp    x2, #0   ; ADR_PREL_PG_HI21 -> .rodata+0x53f
  0x02dc: mov     w8, #1
  0x02e0: add     x9, sp, #0x40
  0x02e4: str     x0, [sp, #0x18]
  0x02e8: add     x2, x2, #0   ; ADD_ABS_LO12_NC -> .rodata+0x53f
  0x02ec: mov     w1, #0x100
  0x02f0: mov     x0, x23
  0x02f4: mov     w3, w22
  0x02f8: mov     w4, w21
  0x02fc: mov     w5, w20
  0x0300: mov     w6, w19
  0x0304: str     w26, [sp, #0x20]
  0x0308: str     w25, [sp, #0x10]
  0x030c: str     w28, [sp, #8]
  0x0310: str     w8, [sp, #0x30]
  0x0314: str     x9, [sp, #0x28]
  0x0318: str     w27, [sp]
  0x031c: bl      #0x31c   ; CALL26 -> snprintf
  0x0320: sxtw    x8, w0
  0x0324: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x66f
  0x0328: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x66f
  0x032c: mov     x1, x23
  0x0330: str     x8, [sp, #0x98]
  0x0334: bl      #0x334   ; CALL26 -> printk
  0x0338: add     x8, sp, #0x60
  0x033c: mov     x0, x23
  0x0340: add     x19, x8, #0x40
  0x0344: bl      #0x344   ; CALL26 -> strlen
  0x0348: mov     x2, x0
  0x034c: mov     x0, x19
  0x0350: mov     x1, x23
  0x0354: bl      #0x354   ; CALL26 -> memcpy
  0x0358: add     x0, sp, #0x60
  0x035c: bl      #0x35c   ; CALL26 -> kevent_send_to_user
  0x0360: cbnz    w0, #0x370
  0x0364: mov     x0, x23
  0x0368: bl      #0x368   ; CALL26 -> kfree
  0x036c: b       #0x230
  0x0370: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x9c4
  0x0374: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x9c4
  0x0378: bl      #0x378   ; CALL26 -> printk
  0x037c: b       #0x364
  0x0380: bl      #0x380   ; CALL26 -> __stack_chk_fail


### oplus_exe_block_ret_handler
=== .text+0x744  (size 0x278) ===

  0x0744: paciasp 
  0x0748: sub     sp, sp, #0x1a0
  0x074c: str     x30, [x18], #8
  0x0750: stp     x29, x30, [sp, #0x150]
  0x0754: str     x28, [sp, #0x160]
  0x0758: stp     x24, x23, [sp, #0x170]
  0x075c: stp     x22, x21, [sp, #0x180]
  0x0760: stp     x20, x19, [sp, #0x190]
  0x0764: add     x29, sp, #0x150
  0x0768: adrp    x8, #0   ; ADR_PREL_PG_HI21 + LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x076c: ldr     x8, [x8]   ; LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x0770: mrs     x20, sp_el0
  0x0774: stur    x8, [x29, #-8]
  0x0778: ldr     x8, [x20, #0xdf8]
  0x077c: cmp     x8, #0xdd
  0x0780: b.ne    #0x838
  0x0784: adrp    x8, #0   ; ADR_PREL_PG_HI21 + LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x0788: ldrb    w8, [x8]   ; LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x078c: tbnz    w8, #0, #0x838
  0x0790: ldr     x8, [x20, #0x518]
  0x0794: mov     w0, #0x200
  0x0798: mov     w1, wzr
  0x079c: ldr     x21, [x8, #0x358]
  0x07a0: bl      #0x7a0   ; CALL26 -> __get_free_pages
  0x07a4: cbz     x0, #0x838
  0x07a8: mov     x19, x0
  0x07ac: add     x0, x21, #0x10
  0x07b0: mov     w2, #0x1000
  0x07b4: mov     x1, x19
  0x07b8: bl      #0x7b8   ; CALL26 -> d_path
  0x07bc: cmn     x0, #1, lsl #12
  0x07c0: b.hi    #0x82c
  0x07c4: adrp    x1, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x308
  0x07c8: add     x1, x1, #0   ; ADD_ABS_LO12_NC -> .rodata+0x308
  0x07cc: mov     w2, #5
  0x07d0: mov     x21, x0
  0x07d4: bl      #0x7d4   ; CALL26 -> strncmp
  0x07d8: cbnz    w0, #0x82c
  0x07dc: adrp    x1, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x823
  0x07e0: add     x1, x1, #0   ; ADD_ABS_LO12_NC -> .rodata+0x823
  0x07e4: mov     w2, #0xf
  0x07e8: mov     x0, x21
  0x07ec: bl      #0x7ec   ; CALL26 -> strncmp
  0x07f0: cbz     w0, #0x824
  0x07f4: adrp    x1, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x35f
  0x07f8: add     x1, x1, #0   ; ADD_ABS_LO12_NC -> .rodata+0x35f
  0x07fc: mov     w2, #0x10
  0x0800: mov     x0, x21
  0x0804: bl      #0x804   ; CALL26 -> strncmp
  0x0808: cbz     w0, #0x824
  0x080c: adrp    x1, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x9f0
  0x0810: add     x1, x1, #0   ; ADD_ABS_LO12_NC -> .rodata+0x9f0
  0x0814: mov     w2, #0x12
  0x0818: mov     x0, x21
  0x081c: bl      #0x81c   ; CALL26 -> strncmp
  0x0820: cbnz    w0, #0x870
  0x0824: mov     x0, x20
  0x0828: bl      #0x828   ; CALL26 -> oplus_RWO_root_check
  0x082c: mov     x0, x19
  0x0830: mov     w1, wzr
  0x0834: bl      #0x834   ; CALL26 -> free_pages
  0x0838: adrp    x9, #0   ; ADR_PREL_PG_HI21 -> __stack_chk_guard
  0x083c: ldur    x8, [x29, #-8]
  0x0840: ldr     x9, [x9]   ; LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x0844: cmp     x9, x8
  0x0848: b.ne    #0x930
  0x084c: ldp     x29, x30, [sp, #0x150]
  0x0850: ldp     x20, x19, [sp, #0x190]
  0x0854: ldp     x22, x21, [sp, #0x180]
  0x0858: ldp     x24, x23, [sp, #0x170]
  0x085c: ldr     x28, [sp, #0x160]
  0x0860: ldr     x30, [x18, #-8]!
  0x0864: add     sp, sp, #0x1a0
  0x0868: autiasp 
  0x086c: ret     
  0x0870: ldr     x22, [x20, #0x780]
  0x0874: add     x0, sp, #8
  0x0878: mov     w2, #0x140
  0x087c: mov     w1, wzr
  0x0880: ldr     w23, [x22, #4]
  0x0884: add     x24, sp, #8
  0x0888: bl      #0x888   ; CALL26 -> memset
  0x088c: adrp    x9, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0xb0f
  0x0890: add     x9, x9, #0   ; ADD_ABS_LO12_NC -> .rodata+0xb0f
  0x0894: ldr     w3, [x22, #4]
  0x0898: ldr     x9, [x9]
  0x089c: mov     w8, #3
  0x08a0: mov     w10, #0x6576
  0x08a4: add     x0, x24, #0x40
  0x08a8: movk    w10, #0x746e, lsl #16
  0x08ac: str     w8, [sp, #8]
  0x08b0: add     x8, x24, #0x24
  0x08b4: stur    xzr, [sp, #0x24]
  0x08b8: stur    xzr, [sp, #0x1c]
  0x08bc: stur    x10, [sp, #0x14]
  0x08c0: stur    x9, [sp, #0xc]
  0x08c4: cbz     w23, #0x934
  0x08c8: adrp    x9, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0xae5
  0x08cc: add     x9, x9, #0   ; ADD_ABS_LO12_NC -> .rodata+0xae5
  0x08d0: ldr     x9, [x9]
  0x08d4: mov     x10, #0x7065
  0x08d8: movk    x10, #0x726f, lsl #16
  0x08dc: adrp    x2, #0   ; ADR_PREL_PG_HI21 -> .rodata+0x415
  0x08e0: movk    x10, #0x74, lsl #32
  0x08e4: add     x2, x2, #0   ; ADD_ABS_LO12_NC -> .rodata+0x415
  0x08e8: mov     w1, #0x100
  0x08ec: mov     x4, x21
  0x08f0: str     wzr, [x8, #0x10]
  0x08f4: stp     x9, x10, [x8]
  0x08f8: bl      #0x8f8   ; CALL26 -> snprintf
  0x08fc: sxtw    x8, w0
  0x0900: cmp     w0, #0x100
  0x0904: cinc    x8, x8, lo
  0x0908: add     x0, sp, #8
  0x090c: str     x8, [sp, #0x40]
  0x0910: bl      #0x910   ; CALL26 -> kevent_send_to_user
  0x0914: adrp    x0, #0   ; ADR_PREL_PG_HI21 -> .rodata+0xaa3
  0x0918: adrp    x2, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x9b6
  0x091c: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0xaa3
  0x0920: add     x2, x2, #0   ; ADD_ABS_LO12_NC -> .rodata+0x9b6
  0x0924: mov     x1, x21
  0x0928: bl      #0x928   ; CALL26 -> printk
  0x092c: b       #0x82c
  0x0930: bl      #0x930   ; CALL26 -> __stack_chk_fail
  0x0934: adrp    x9, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0xafa
  0x0938: add     x9, x9, #0   ; ADD_ABS_LO12_NC -> .rodata+0xafa
  0x093c: ldr     x9, [x9]
  0x0940: mov     w10, #0x6f6c
  0x0944: adrp    x2, #0   ; ADR_PREL_PG_HI21 -> .rodata+0x415
  0x0948: movk    w10, #0x6b63, lsl #16
  0x094c: add     x2, x2, #0   ; ADD_ABS_LO12_NC -> .rodata+0x415
  0x0950: mov     w1, #0x100
  0x0954: mov     x4, x21
  0x0958: str     wzr, [x8, #0x10]
  0x095c: stp     x9, x10, [x8]
  0x0960: bl      #0x960   ; CALL26 -> snprintf
  0x0964: sxtw    x8, w0
  0x0968: cmp     w0, #0x100
  0x096c: cinc    x8, x8, lo
  0x0970: add     x0, sp, #8
  0x0974: str     x8, [sp, #0x40]
  0x0978: bl      #0x978   ; CALL26 -> kevent_send_to_user
  0x097c: adrp    x0, #0   ; ADR_PREL_PG_HI21 -> .rodata+0xaa3
  0x0980: adrp    x2, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x30e
  0x0984: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0xaa3
  0x0988: add     x2, x2, #0   ; ADD_ABS_LO12_NC -> .rodata+0x30e
  0x098c: mov     x1, x21
  0x0990: bl      #0x990   ; CALL26 -> printk
  0x0994: mov     x0, x19
  0x0998: mov     w1, wzr
  0x099c: bl      #0x99c   ; CALL26 -> free_pages
  0x09a0: ldr     x2, [x20, #0xdf8]
  0x09a4: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x8da
  0x09a8: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x8da
  0x09ac: mov     w1, #-1
  0x09b0: bl      #0x9b0   ; CALL26 -> printk
  0x09b4: mov     w0, #9
  0x09b8: bl      #0x9b8   ; CALL26 -> do_exit


### oplus_RWO_root_check
=== .text+0x538  (size 0x208) ===

  0x0538: paciasp 
  0x053c: sub     sp, sp, #0xc0
  0x0540: str     x30, [x18], #8
  0x0544: stp     x29, x30, [sp, #0x90]
  0x0548: stp     x22, x21, [sp, #0xa0]
  0x054c: stp     x20, x19, [sp, #0xb0]
  0x0550: add     x29, sp, #0x90
  0x0554: adrp    x8, #0   ; ADR_PREL_PG_HI21 + LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x0558: ldr     x8, [x8]   ; LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x055c: stur    x8, [x29, #-8]
  0x0560: stp     xzr, xzr, [sp, #0x78]
  0x0564: stp     xzr, xzr, [sp, #0x68]
  0x0568: stp     xzr, xzr, [sp, #0x58]
  0x056c: stp     xzr, xzr, [sp, #0x48]
  0x0570: stp     xzr, xzr, [sp, #0x38]
  0x0574: stp     xzr, xzr, [sp, #0x28]
  0x0578: stp     xzr, xzr, [sp, #0x18]
  0x057c: stp     xzr, xzr, [sp, #8]
  0x0580: cbz     x0, #0x598
  0x0584: ldr     w8, [x0, #0x5c8]
  0x0588: mov     x19, x0
  0x058c: cmp     w8, #1
  0x0590: b.ne    #0x5c8
  0x0594: mov     w0, wzr
  0x0598: adrp    x9, #0   ; ADR_PREL_PG_HI21 -> __stack_chk_guard
  0x059c: ldur    x8, [x29, #-8]
  0x05a0: ldr     x9, [x9]   ; LDST64_ABS_LO12_NC -> __stack_chk_guard
  0x05a4: cmp     x9, x8
  0x05a8: b.ne    #0x70c
  0x05ac: ldp     x29, x30, [sp, #0x90]
  0x05b0: ldp     x20, x19, [sp, #0xb0]
  0x05b4: ldp     x22, x21, [sp, #0xa0]
  0x05b8: ldr     x30, [x18, #-8]!
  0x05bc: add     sp, sp, #0xc0
  0x05c0: autiasp 
  0x05c4: ret     
  0x05c8: ldr     x9, [x19, #0x780]
  0x05cc: ldr     w10, [x9, #4]
  0x05d0: cbz     w10, #0x5ec
  0x05d4: ldr     w10, [x9, #8]
  0x05d8: cbz     w10, #0x5ec
  0x05dc: ldr     w10, [x9, #0x14]
  0x05e0: cbz     w10, #0x5ec
  0x05e4: ldr     w9, [x9, #0x18]
  0x05e8: cbnz    w9, #0x594
  0x05ec: ldr     w0, [x19, #0x5cc]
  0x05f0: cmp     w0, w8
  0x05f4: b.ne    #0x678
  0x05f8: add     x8, x19, #0x5d8
  0x05fc: ldar    x22, [x8]
  0x0600: ldr     x8, [x22, #0x780]
  0x0604: ldr     w9, [x8, #4]
  0x0608: cbz     w9, #0x594
  0x060c: ldr     w9, [x8, #8]
  0x0610: cbz     w9, #0x594
  0x0614: ldr     w9, [x8, #0x14]
  0x0618: cbz     w9, #0x594
  0x061c: ldr     w8, [x8, #0x18]
  0x0620: cbz     w8, #0x594
  0x0624: add     x20, x22, #0x790
  0x0628: add     x21, x19, #0x790
  0x062c: adrp    x1, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x8c6
  0x0630: add     x1, x1, #0   ; ADD_ABS_LO12_NC -> .rodata+0x8c6
  0x0634: add     x0, sp, #8
  0x0638: mov     x2, x20
  0x063c: mov     x3, x21
  0x0640: bl      #0x640   ; CALL26 -> sprintf
  0x0644: ldr     x8, [x19, #0x780]
  0x0648: ldr     x9, [x22, #0x780]
  0x064c: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x833
  0x0650: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x833
  0x0654: ldr     w2, [x8, #4]
  0x0658: ldr     w4, [x9, #4]
  0x065c: mov     x1, x21
  0x0660: mov     x3, x20
  0x0664: bl      #0x664   ; CALL26 -> printk
  0x0668: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0xa9d
  0x066c: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0xa9d
  0x0670: add     x2, sp, #8
  0x0674: b       #0x6f0
  0x0678: bl      #0x678   ; CALL26 -> find_task_by_vpid
  0x067c: mov     x8, x0
  0x0680: add     x0, x0, #0x40
  0x0684: b       #0x710
  0x0688: b       #0x710
  0x068c: mov     w9, #1
  0x0690: ldadd   w9, w9, [x0]
  0x0694: cbz     w9, #0x72c
  0x0698: add     w10, w9, #1
  0x069c: orr     w9, w10, w9
  0x06a0: tbnz    w9, #0x1f, #0x700
  0x06a4: ldr     x8, [x8, #0x780]
  0x06a8: ldr     w3, [x8, #4]
  0x06ac: cbz     w3, #0x594
  0x06b0: ldr     w9, [x8, #8]
  0x06b4: cbz     w9, #0x594
  0x06b8: ldr     w9, [x8, #0x14]
  0x06bc: cbz     w9, #0x594
  0x06c0: ldr     w8, [x8, #0x18]
  0x06c4: cbz     w8, #0x594
  0x06c8: ldr     x8, [x19, #0x780]
  0x06cc: adrp    x0, #0   ; ADR_PREL_PG_HI21 -> .rodata+0x880
  0x06d0: add     x1, x19, #0x790
  0x06d4: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x880
  0x06d8: ldr     w2, [x8, #4]
  0x06dc: bl      #0x6dc   ; CALL26 -> printk
  0x06e0: adrp    x0, #0   ; ADR_PREL_PG_HI21 -> .rodata+0xa9d
  0x06e4: adrp    x2, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x9ef
  0x06e8: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0xa9d
  0x06ec: add     x2, x2, #0   ; ADD_ABS_LO12_NC -> .rodata+0x9ef
  0x06f0: mov     w1, #0xe
  0x06f4: bl      #0x6f4   ; CALL26 -> report_secuiry_event
  0x06f8: mov     w0, #1
  0x06fc: b       #0x598
  0x0700: mov     x20, x8
  0x0704: mov     w1, #1
  0x0708: b       #0x734
  0x070c: bl      #0x70c   ; CALL26 -> __stack_chk_fail
  0x0710: bti     j
  0x0714: prfm    pstl1strm, [x0]
  0x0718: ldxr    w9, [x0]
  0x071c: add     w10, w9, #1
  0x0720: stxr    w11, w10, [x0]
  0x0724: cbnz    w11, #0x718
  0x0728: cbnz    w9, #0x698
  0x072c: mov     x20, x8
  0x0730: mov     w1, #2
  0x0734: bl      #0x734   ; CALL26 -> refcount_warn_saturate
  0x0738: mov     x8, x20
  0x073c: b       #0x6a4


### oplus_harden_pre_handler
=== .text+0x9bc  (size 0x2c4) ===

  0x09bc: paciasp 
  0x09c0: str     x30, [x18], #8
  0x09c4: stp     x29, x30, [sp, #-0x30]!
  0x09c8: stp     x22, x21, [sp, #0x10]
  0x09cc: stp     x20, x19, [sp, #0x20]
  0x09d0: mov     x29, sp
  0x09d4: adrp    x8, #0   ; ADR_PREL_PG_HI21 + LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x09d8: ldrb    w8, [x8]   ; LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x09dc: tbz     w8, #0, #0x9fc
  0x09e0: bti     j
  0x09e4: ldp     x20, x19, [sp, #0x20]
  0x09e8: ldp     x22, x21, [sp, #0x10]
  0x09ec: ldp     x29, x30, [sp], #0x30
  0x09f0: ldr     x30, [x18, #-8]!
  0x09f4: autiasp 
  0x09f8: ret     
  0x09fc: ldr     w8, [x1, #0x118]
  0x0a00: sub     w8, w8, #0x8f
  0x0a04: cmp     w8, #6
  0x0a08: b.hi    #0x9e0
  0x0a0c: adrp    x9, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x120
  0x0a10: add     x9, x9, #0   ; ADD_ABS_LO12_NC -> .rodata+0x120
  0x0a14: adr     x10, #0xa14
  0x0a18: ldrsw   x11, [x9, x8, lsl #2]
  0x0a1c: add     x10, x10, x11
  0x0a20: br      x10
  0x0a24: bti     j
  0x0a28: mrs     x8, sp_el0
  0x0a2c: ldr     x8, [x8, #0x780]
  0x0a30: ldr     w19, [x1]
  0x0a34: ldr     w20, [x1, #8]
  0x0a38: mov     w0, #6
  0x0a3c: ldr     w21, [x8, #4]
  0x0a40: bl      #0xa40   ; CALL26 -> capable
  0x0a44: lsr     w8, w21, #4
  0x0a48: cmp     w8, #0x271
  0x0a4c: b.lo    #0x9e0
  0x0a50: tbz     w0, #0, #0x9e0
  0x0a54: cbz     w19, #0xa5c
  0x0a58: cbnz    w20, #0x9e0
  0x0a5c: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x370
  0x0a60: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x370
  0x0a64: mov     w1, w21
  0x0a68: mov     w2, w19
  0x0a6c: mov     w3, w20
  0x0a70: bl      #0xa70   ; CALL26 -> printk
  0x0a74: mov     w3, #2
  0x0a78: mov     w4, #4
  0x0a7c: b       #0xb34
  0x0a80: bti     j
  0x0a84: mrs     x8, sp_el0
  0x0a88: ldr     x8, [x8, #0x780]
  0x0a8c: ldr     w20, [x1]
  0x0a90: mov     w0, #6
  0x0a94: ldr     w19, [x8, #8]
  0x0a98: bl      #0xa98   ; CALL26 -> capable
  0x0a9c: lsr     w8, w19, #4
  0x0aa0: cmp     w8, #0x271
  0x0aa4: b.lo    #0x9e0
  0x0aa8: tbz     w0, #0, #0x9e0
  0x0aac: cbnz    w20, #0x9e0
  0x0ab0: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0xa03
  0x0ab4: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0xa03
  0x0ab8: mov     w1, w19
  0x0abc: mov     w2, wzr
  0x0ac0: bl      #0xac0   ; CALL26 -> printk
  0x0ac4: mov     w3, #1
  0x0ac8: mov     w4, #3
  0x0acc: mov     w0, wzr
  0x0ad0: mov     w1, wzr
  0x0ad4: mov     w2, wzr
  0x0ad8: b       #0xc78
  0x0adc: bti     j
  0x0ae0: mrs     x8, sp_el0
  0x0ae4: ldr     x8, [x8, #0x780]
  0x0ae8: ldr     w19, [x1]
  0x0aec: ldr     w20, [x1, #8]
  0x0af0: mov     w0, #7
  0x0af4: ldr     w21, [x8, #4]
  0x0af8: bl      #0xaf8   ; CALL26 -> capable
  0x0afc: lsr     w8, w21, #4
  0x0b00: cmp     w8, #0x271
  0x0b04: b.lo    #0x9e0
  0x0b08: tbz     w0, #0, #0x9e0
  0x0b0c: cbz     w19, #0xb14
  0x0b10: cbnz    w20, #0x9e0
  0x0b14: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x6a6
  0x0b18: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x6a6
  0x0b1c: mov     w1, w21
  0x0b20: mov     w2, w19
  0x0b24: mov     w3, w20
  0x0b28: bl      #0xb28   ; CALL26 -> printk
  0x0b2c: mov     w3, #2
  0x0b30: mov     w4, #1
  0x0b34: mov     w0, w19
  0x0b38: mov     w1, w20
  0x0b3c: mov     w2, w19
  0x0b40: b       #0xc78
  0x0b44: bti     j
  0x0b48: mrs     x8, sp_el0
  0x0b4c: ldr     x8, [x8, #0x780]
  0x0b50: ldr     w20, [x1]
  0x0b54: mov     w0, #7
  0x0b58: ldr     w19, [x8, #4]
  0x0b5c: bl      #0xb5c   ; CALL26 -> capable
  0x0b60: lsr     w8, w19, #4
  0x0b64: cmp     w8, #0x271
  0x0b68: b.lo    #0x9e0
  0x0b6c: tbz     w0, #0, #0x9e0
  0x0b70: cbnz    w20, #0x9e0
  0x0b74: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x916
  0x0b78: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x916
  0x0b7c: mov     w1, w19
  0x0b80: mov     w2, wzr
  0x0b84: bl      #0xb84   ; CALL26 -> printk
  0x0b88: mov     w3, #1
  0x0b8c: mov     w0, wzr
  0x0b90: mov     w1, wzr
  0x0b94: mov     w2, wzr
  0x0b98: mov     w4, wzr
  0x0b9c: b       #0xc78
  0x0ba0: bti     j
  0x0ba4: mrs     x8, sp_el0
  0x0ba8: ldr     x8, [x8, #0x780]
  0x0bac: ldr     w19, [x1]
  0x0bb0: ldr     w20, [x1, #8]
  0x0bb4: ldr     w21, [x1, #0x10]
  0x0bb8: ldr     w22, [x8, #4]
  0x0bbc: mov     w0, #7
  0x0bc0: bl      #0xbc0   ; CALL26 -> capable
  0x0bc4: lsr     w8, w22, #4
  0x0bc8: cmp     w8, #0x271
  0x0bcc: b.lo    #0x9e0
  0x0bd0: tbz     w0, #0, #0x9e0
  0x0bd4: cbz     w19, #0xbe0
  0x0bd8: cbz     w20, #0xbe0
  0x0bdc: cbnz    w21, #0x9e0
  0x0be0: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x13c
  0x0be4: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x13c
  0x0be8: mov     w1, w22
  0x0bec: mov     w2, w19
  0x0bf0: mov     w3, w20
  0x0bf4: mov     w4, w21
  0x0bf8: bl      #0xbf8   ; CALL26 -> printk
  0x0bfc: mov     w3, #4
  0x0c00: mov     w4, #2
  0x0c04: b       #0xc6c
  0x0c08: bti     j
  0x0c0c: mrs     x8, sp_el0
  0x0c10: ldr     x8, [x8, #0x780]
  0x0c14: ldr     w19, [x1]
  0x0c18: ldr     w20, [x1, #8]
  0x0c1c: ldr     w21, [x1, #0x10]
  0x0c20: ldr     w22, [x8, #8]
  0x0c24: mov     w0, #6
  0x0c28: bl      #0xc28   ; CALL26 -> capable
  0x0c2c: lsr     w8, w22, #4
  0x0c30: cmp     w8, #0x271
  0x0c34: b.lo    #0x9e0
  0x0c38: tbz     w0, #0, #0x9e0
  0x0c3c: cbz     w19, #0xc48
  0x0c40: cbz     w20, #0xc48
  0x0c44: cbnz    w21, #0x9e0
  0x0c48: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x421
  0x0c4c: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x421
  0x0c50: mov     w1, w22
  0x0c54: mov     w2, w19
  0x0c58: mov     w3, w20
  0x0c5c: mov     w4, w21
  0x0c60: bl      #0xc60   ; CALL26 -> printk
  0x0c64: mov     w3, #4
  0x0c68: mov     w4, #5
  0x0c6c: mov     w0, w19
  0x0c70: mov     w1, w20
  0x0c74: mov     w2, w21
  0x0c78: bl      #0xc78   ; CALL26 -> .text+0xc80
  0x0c7c: b       #0x9e0


### oplus_boot_state_init
=== .text+0x4c8  (size 0x64) ===

  0x04c8: paciasp 
  0x04cc: str     x30, [x18], #8
  0x04d0: stp     x29, x30, [sp, #-0x20]!
  0x04d4: str     x19, [sp, #0x10]
  0x04d8: mov     x29, sp
  0x04dc: adrp    x19, #0   ; ADR_PREL_PG_HI21 -> verified_bootstate
  0x04e0: adrp    x0, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x7f1
  0x04e4: add     x19, x19, #0   ; ADD_ABS_LO12_NC -> verified_bootstate
  0x04e8: add     x0, x0, #0   ; ADD_ABS_LO12_NC -> .rodata+0x7f1
  0x04ec: mov     x1, x19
  0x04f0: bl      #0x4f0   ; CALL26 -> printk
  0x04f4: adrp    x1, #0   ; ADR_PREL_PG_HI21 + ADD_ABS_LO12_NC -> .rodata+0x9af
  0x04f8: add     x1, x1, #0   ; ADD_ABS_LO12_NC -> .rodata+0x9af
  0x04fc: mov     x0, x19
  0x0500: bl      #0x500   ; CALL26 -> strstr
  0x0504: ldr     x19, [sp, #0x10]
  0x0508: cmp     x0, #0
  0x050c: cset    w8, ne
  0x0510: adrp    x9, #0   ; ADR_PREL_PG_HI21 + LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x0514: strb    w8, [x9]   ; LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x0518: mov     w0, wzr
  0x051c: ldp     x29, x30, [sp], #0x20
  0x0520: ldr     x30, [x18, #-8]!
  0x0524: autiasp 
  0x0528: ret     


### is_unlocked
=== .text+0x4b4  (size 0x14) ===

  0x04b4: paciasp 
  0x04b8: adrp    x8, #0   ; ADR_PREL_PG_HI21 + LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x04bc: ldrb    w0, [x8]   ; LDST8_ABS_LO12_NC -> .data..ro_after_init
  0x04c0: autiasp 
  0x04c4: ret     


==============================================================================
== kill-path jump table (.rodata+0), with the real arm64 syscall names
==============================================================================

# oplus_security_guard.ko - kill-path jump table @ .rodata+0
# 72 entries, syscall 143..214
# target = 0x47c + int32(table[idx]); 0x48c = return (no kill), 0x4a0 = report + do_exit(SIGKILL)

   nr  syscall            target    verdict
  143  setregid           0x48c     EXEMPT (no kill)
  144  setgid             0x48c     EXEMPT (no kill)
  145  setreuid           0x48c     EXEMPT (no kill)
  146  setuid             0x48c     EXEMPT (no kill)
  147  setresuid          0x48c     EXEMPT (no kill)
  148  getresuid          0x4a0     report+kill
  149  setresgid          0x48c     EXEMPT (no kill)
  150  getresgid          0x4a0     report+kill
  151  setfsuid           0x4a0     report+kill
  152  setfsgid           0x4a0     report+kill
  153  times              0x4a0     report+kill
  154  setpgid            0x4a0     report+kill
  155  getpgid            0x4a0     report+kill
  156  getsid             0x4a0     report+kill
  157  setsid             0x4a0     report+kill
  158  getgroups          0x4a0     report+kill
  159  setgroups          0x4a0     report+kill
  160  uname              0x4a0     report+kill
  161  sethostname        0x4a0     report+kill
  162  setdomainname      0x4a0     report+kill
  163  getrlimit          0x4a0     report+kill
  164  setrlimit          0x4a0     report+kill
  165  getrusage          0x4a0     report+kill
  166  umask              0x4a0     report+kill
  167  prctl              0x4a0     report+kill
  168  getcpu             0x4a0     report+kill
  169  gettimeofday       0x4a0     report+kill
  170  settimeofday       0x4a0     report+kill
  171  adjtimex           0x4a0     report+kill
  172  getpid             0x4a0     report+kill
  173  getppid            0x4a0     report+kill
  174  getuid             0x4a0     report+kill
  175  geteuid            0x4a0     report+kill
  176  getgid             0x4a0     report+kill
  177  getegid            0x4a0     report+kill
  178  gettid             0x4a0     report+kill
  179  sysinfo            0x4a0     report+kill
  180  mq_open            0x4a0     report+kill
  181  mq_unlink          0x4a0     report+kill
  182  mq_timedsend       0x4a0     report+kill
  183  mq_timedreceive    0x4a0     report+kill
  184  mq_notify          0x4a0     report+kill
  185  mq_getsetattr      0x4a0     report+kill
  186  msgget             0x4a0     report+kill
  187  msgctl             0x4a0     report+kill
  188  msgrcv             0x4a0     report+kill
  189  msgsnd             0x4a0     report+kill
  190  semget             0x4a0     report+kill
  191  semctl             0x4a0     report+kill
  192  semtimedop         0x4a0     report+kill
  193  semop              0x4a0     report+kill
  194  shmget             0x4a0     report+kill
  195  shmctl             0x4a0     report+kill
  196  shmat              0x4a0     report+kill
  197  shmdt              0x4a0     report+kill
  198  socket             0x4a0     report+kill
  199  socketpair         0x4a0     report+kill
  200  bind               0x4a0     report+kill
  201  listen             0x4a0     report+kill
  202  accept             0x4a0     report+kill
  203  connect            0x48c     EXEMPT (no kill)
  204  getsockname        0x48c     EXEMPT (no kill)
  205  getpeername        0x4a0     report+kill
  206  sendto             0x4a0     report+kill
  207  recvfrom           0x4a0     report+kill
  208  setsockopt         0x48c     EXEMPT (no kill)
  209  getsockopt         0x4a0     report+kill
  210  shutdown           0x48c     EXEMPT (no kill)
  211  sendmsg            0x4a0     report+kill
  212  recvmsg            0x4a0     report+kill
  213  readahead          0x48c     EXEMPT (no kill)
  214  brk                0x48c     EXEMPT (no kill)

# EXEMPT (12): 143 144 145 146 147 149 203 204 208 210 213 214
# 143 setregid 144 setgid 145 setreuid 146 setuid 147 setresuid 149 setresgid 203 connect 204 getsockname 208 setsockopt 210 shutdown 213 readahead 214 brk

# relocations for .text: 214 entries
# offset     type                   target
  0x4c       ADR_PREL_PG_HI21       .text+0xfc0
  0x50       ADD_ABS_LO12_NC        .text+0xfc0
  0x98       ADR_PREL_PG_HI21       .text+0xfb0
  0x9c       ADD_ABS_LO12_NC        .text+0xfb0
  0xa4       ADR_PREL_PG_HI21       .text+0xfb8
  0xa8       ADD_ABS_LO12_NC        .text+0xfb8
  0xb0       ADR_PREL_PG_HI21       .text+0xfa8
  0xb4       ADD_ABS_LO12_NC        .text+0xfa8
  0xd0       CALL26                 __cfi_check_fail
  0x128      ADR_PREL_PG_HI21       .data+0x10
  0x12c      ADD_ABS_LO12_NC        .data+0x10
  0x13c      ADR_PREL_PG_HI21       .data+0x40
  0x140      ADD_ABS_LO12_NC        .data+0x40
  0x174      ADR_PREL_PG_HI21       __stack_chk_guard
  0x178      LDST64_ABS_LO12_NC     __stack_chk_guard
  0x19c      CALL26                 memset
  0x1c4      CALL26                 __get_task_comm
  0x1d8      ADR_PREL_PG_HI21       .rodata+0xb0f
  0x1e0      ADD_ABS_LO12_NC        .rodata+0xb0f
  0x1ec      ADR_PREL_PG_HI21       .rodata+0xad0
  0x1f0      ADD_ABS_LO12_NC        .rodata+0xad0
  0x1fc      ADR_PREL_PG_HI21       kmalloc_caches+0x40
  0x200      LDST64_ABS_LO12_NC     kmalloc_caches+0x40
  0x228      CALL26                 kmem_cache_alloc_trace
  0x230      ADR_PREL_PG_HI21       __stack_chk_guard
  0x238      LDST64_ABS_LO12_NC     __stack_chk_guard
  0x2d0      CALL26                 __get_task_comm
  0x2d8      ADR_PREL_PG_HI21       .rodata+0x53f
  0x2e8      ADD_ABS_LO12_NC        .rodata+0x53f
  0x31c      CALL26                 snprintf
  0x324      ADR_PREL_PG_HI21       .rodata+0x66f
  0x328      ADD_ABS_LO12_NC        .rodata+0x66f
  0x334      CALL26                 printk
  0x344      CALL26                 strlen
  0x354      CALL26                 memcpy
  0x35c      CALL26                 kevent_send_to_user
  0x368      CALL26                 kfree
  0x370      ADR_PREL_PG_HI21       .rodata+0x9c4
  0x374      ADD_ABS_LO12_NC        .rodata+0x9c4
  0x378      CALL26                 printk
  0x380      CALL26                 __stack_chk_fail
  0x398      ADR_PREL_PG_HI21       .rodata+0x976
  0x39c      ADD_ABS_LO12_NC        .rodata+0x976
  0x3a0      CALL26                 printk
  0x3a8      CALL26                 do_exit
  0x404      ADR_PREL_PG_HI21       .data..ro_after_init
  0x408      LDST8_ABS_LO12_NC      .data..ro_after_init
  0x474      ADR_PREL_PG_HI21       .rodata
  0x478      ADD_ABS_LO12_NC        .rodata
  0x4ac      CALL26                 oplus_root_check_succ
  0x4b0      CALL26                 oplus_root_killed
  0x4b8      ADR_PREL_PG_HI21       .data..ro_after_init
  0x4bc      LDST8_ABS_LO12_NC      .data..ro_after_init
  0x4dc      ADR_PREL_PG_HI21       verified_bootstate
  0x4e0      ADR_PREL_PG_HI21       .rodata+0x7f1
  0x4e4      ADD_ABS_LO12_NC        verified_bootstate
  0x4e8      ADD_ABS_LO12_NC        .rodata+0x7f1
  0x4f0      CALL26                 printk
  0x4f4      ADR_PREL_PG_HI21       .rodata+0x9af
  0x4f8      ADD_ABS_LO12_NC        .rodata+0x9af
  0x500      CALL26                 strstr
  0x510      ADR_PREL_PG_HI21       .data..ro_after_init
  0x514      LDST8_ABS_LO12_NC      .data..ro_after_init
  0x554      ADR_PREL_PG_HI21       __stack_chk_guard
  0x558      LDST64_ABS_LO12_NC     __stack_chk_guard
  0x598      ADR_PREL_PG_HI21       __stack_chk_guard
  0x5a0      LDST64_ABS_LO12_NC     __stack_chk_guard
  0x62c      ADR_PREL_PG_HI21       .rodata+0x8c6
  0x630      ADD_ABS_LO12_NC        .rodata+0x8c6
  0x640      CALL26                 sprintf
  0x64c      ADR_PREL_PG_HI21       .rodata+0x833
  0x650      ADD_ABS_LO12_NC        .rodata+0x833
  0x664      CALL26                 printk
  0x668      ADR_PREL_PG_HI21       .rodata+0xa9d
  0x66c      ADD_ABS_LO12_NC        .rodata+0xa9d
  0x678      CALL26                 find_task_by_vpid
  0x6cc      ADR_PREL_PG_HI21       .rodata+0x880
  0x6d4      ADD_ABS_LO12_NC        .rodata+0x880
  0x6dc      CALL26                 printk
  0x6e0      ADR_PREL_PG_HI21       .rodata+0xa9d
  0x6e4      ADR_PREL_PG_HI21       .rodata+0x9ef
  0x6e8      ADD_ABS_LO12_NC        .rodata+0xa9d
  0x6ec      ADD_ABS_LO12_NC        .rodata+0x9ef
  0x6f4      CALL26                 report_secuiry_event
  0x70c      CALL26                 __stack_chk_fail
  0x734      CALL26                 refcount_warn_saturate
  0x768      ADR_PREL_PG_HI21       __stack_chk_guard
  0x76c      LDST64_ABS_LO12_NC     __stack_chk_guard
  0x784      ADR_PREL_PG_HI21       .data..ro_after_init
  0x788      LDST8_ABS_LO12_NC      .data..ro_after_init
  0x7a0      CALL26                 __get_free_pages
  0x7b8      CALL26                 d_path
  0x7c4      ADR_PREL_PG_HI21       .rodata+0x308
  0x7c8      ADD_ABS_LO12_NC        .rodata+0x308
  0x7d4      CALL26                 strncmp
  0x7dc      ADR_PREL_PG_HI21       .rodata+0x823
  0x7e0      ADD_ABS_LO12_NC        .rodata+0x823
  0x7ec      CALL26                 strncmp
  0x7f4      ADR_PREL_PG_HI21       .rodata+0x35f
  0x7f8      ADD_ABS_LO12_NC        .rodata+0x35f
  0x804      CALL26                 strncmp
  0x80c      ADR_PREL_PG_HI21       .rodata+0x9f0
  0x810      ADD_ABS_LO12_NC        .rodata+0x9f0
  0x81c      CALL26                 strncmp
  0x828      CALL26                 oplus_RWO_root_check
  0x834      CALL26                 free_pages
  0x838      ADR_PREL_PG_HI21       __stack_chk_guard
  0x840      LDST64_ABS_LO12_NC     __stack_chk_guard
  0x888      CALL26                 memset
  0x88c      ADR_PREL_PG_HI21       .rodata+0xb0f
  0x890      ADD_ABS_LO12_NC        .rodata+0xb0f
  0x8c8      ADR_PREL_PG_HI21       .rodata+0xae5
  0x8cc      ADD_ABS_LO12_NC        .rodata+0xae5
  0x8dc      ADR_PREL_PG_HI21       .rodata+0x415
  0x8e4      ADD_ABS_LO12_NC        .rodata+0x415
  0x8f8      CALL26                 snprintf
  0x910      CALL26                 kevent_send_to_user
  0x914      ADR_PREL_PG_HI21       .rodata+0xaa3
  0x918      ADR_PREL_PG_HI21       .rodata+0x9b6
  0x91c      ADD_ABS_LO12_NC        .rodata+0xaa3
  0x920      ADD_ABS_LO12_NC        .rodata+0x9b6
  0x928      CALL26                 printk
  0x930      CALL26                 __stack_chk_fail
  0x934      ADR_PREL_PG_HI21       .rodata+0xafa
  0x938      ADD_ABS_LO12_NC        .rodata+0xafa
  0x944      ADR_PREL_PG_HI21       .rodata+0x415
  0x94c      ADD_ABS_LO12_NC        .rodata+0x415
  0x960      CALL26                 snprintf
  0x978      CALL26                 kevent_send_to_user
  0x97c      ADR_PREL_PG_HI21       .rodata+0xaa3
  0x980      ADR_PREL_PG_HI21       .rodata+0x30e
  0x984      ADD_ABS_LO12_NC        .rodata+0xaa3
  0x988      ADD_ABS_LO12_NC        .rodata+0x30e
  0x990      CALL26                 printk
  0x99c      CALL26                 free_pages
  0x9a4      ADR_PREL_PG_HI21       .rodata+0x8da
  0x9a8      ADD_ABS_LO12_NC        .rodata+0x8da
  0x9b0      CALL26                 printk
  0x9b8      CALL26                 do_exit
  0x9d4      ADR_PREL_PG_HI21       .data..ro_after_init
  0x9d8      LDST8_ABS_LO12_NC      .data..ro_after_init
  0xa0c      ADR_PREL_PG_HI21       .rodata+0x120
  0xa10      ADD_ABS_LO12_NC        .rodata+0x120
  0xa40      CALL26                 capable
  0xa5c      ADR_PREL_PG_HI21       .rodata+0x370
  0xa60      ADD_ABS_LO12_NC        .rodata+0x370
  0xa70      CALL26                 printk
  0xa98      CALL26                 capable
  0xab0      ADR_PREL_PG_HI21       .rodata+0xa03
  0xab4      ADD_ABS_LO12_NC        .rodata+0xa03
  0xac0      CALL26                 printk
  0xaf8      CALL26                 capable
  0xb14      ADR_PREL_PG_HI21       .rodata+0x6a6
  0xb18      ADD_ABS_LO12_NC        .rodata+0x6a6
  0xb28      CALL26                 printk
  0xb5c      CALL26                 capable
  0xb74      ADR_PREL_PG_HI21       .rodata+0x916
  0xb78      ADD_ABS_LO12_NC        .rodata+0x916
  0xb84      CALL26                 printk
  0xbc0      CALL26                 capable
  0xbe0      ADR_PREL_PG_HI21       .rodata+0x13c
  0xbe4      ADD_ABS_LO12_NC        .rodata+0x13c
  0xbf8      CALL26                 printk
  0xc28      CALL26                 capable
  0xc48      ADR_PREL_PG_HI21       .rodata+0x421
  0xc4c      ADD_ABS_LO12_NC        .rodata+0x421
  0xc60      CALL26                 printk
  0xc78      CALL26                 .text+0xc80
  0xca8      ADR_PREL_PG_HI21       __stack_chk_guard
  0xcac      LDST64_ABS_LO12_NC     __stack_chk_guard
  0xcd8      CALL26                 memset
  0xce4      ADR_PREL_PG_HI21       .rodata+0xb0f
  0xcec      ADD_ABS_LO12_NC        .rodata+0xb0f
  0xd08      ADR_PREL_PG_HI21       .rodata+0xb30
  0xd0c      ADD_ABS_LO12_NC        .rodata+0xb30
  0xd14      ADR_PREL_PG_HI21       kmalloc_caches+0x40
  0xd1c      LDST64_ABS_LO12_NC     kmalloc_caches+0x40
  0xd3c      CALL26                 kmem_cache_alloc_trace
  0xd44      ADR_PREL_PG_HI21       __stack_chk_guard
  0xd4c      LDST64_ABS_LO12_NC     __stack_chk_guard
  0xdf0      CALL26                 __get_task_comm
  0xdf4      ADR_PREL_PG_HI21       .rodata+0x5e5
  0xe08      ADD_ABS_LO12_NC        .rodata+0x5e5
  0xe30      CALL26                 __get_task_comm
  0xe40      ADR_PREL_PG_HI21       .rodata+0x20c
  0xe50      ADD_ABS_LO12_NC        .rodata+0x20c
  0xe58      ADR_PREL_PG_HI21       .rodata+0x71c
  0xe5c      ADD_ABS_LO12_NC        .rodata+0x71c
  0xe90      CALL26                 snprintf
  0xe98      ADR_PREL_PG_HI21       .rodata+0x4ef
  0xe9c      ADD_ABS_LO12_NC        .rodata+0x4ef
  0xea8      CALL26                 printk
  0xeb8      CALL26                 strlen
  0xec8      CALL26                 memcpy
  0xed0      CALL26                 kevent_send_to_user
  0xedc      CALL26                 kfree
  0xee4      ADR_PREL_PG_HI21       .rodata+0x3e6
  0xee8      ADD_ABS_LO12_NC        .rodata+0x3e6
  0xeec      CALL26                 printk
  0xef4      CALL26                 __stack_chk_fail
  0xf18      ADR_PREL_PG_HI21       .data..ro_after_init
  0xf1c      LDST8_ABS_LO12_NC      .data..ro_after_init
  0xf5c      CALL26                 capable
  0xf8c      CALL26                 .text+0xc80
  0xf90      ADR_PREL_PG_HI21       .rodata+0x7a2
  0xf94      ADD_ABS_LO12_NC        .rodata+0x7a2
  0xfa0      CALL26                 printk
  0xfac      JUMP26                 init_module
  0xfb4      JUMP26                 cleanup_module
  0xfbc      JUMP26                 oplus_RWO_root_check
  0xfc4      JUMP26                 oplus_root_check_pre_handler
  0xfcc      JUMP26                 oplus_root_check_post_handler
  0xfd4      JUMP26                 oplus_exe_block_ret_handler
  0xfdc      JUMP26                 oplus_harden_pre_handler

